### ISSUE TITLE
Possible bug in the BuildPluginView.xaml.cs. 

### ISSUE THREAD

**Issue by nairdo** [cabal95/RockDevBooster#1]
Should this use the file name you selected?
https://github.com/cabal95/RockDevBooster/blob/1ce17f2c65895d2f864a72ec06b2d0aa020ddbd6/RockDevBooster/Views/BuildPluginView.xaml.cs#L227

...and be more like this: 
```csharp
          var pluginJson = File.ReadAllText( openFileDialog.FileName );
```
or are all our builder files supposed to be called `rockplugin.json`?

**Comment by cabal95** [comment]
It should be using the selected file name.  I'll push a fix for that in a few minutes. I've been naming all my files `rockplugin.json` so I haven't run into that issue yet. :)
